export const WARDS: Array<string> = [
    'Adogi',
    'Adudu',
    'Agada/bagaji',
    'Agaza',
    'Agbashi',
    'Agunji',
    'Agwada',
    'Agwatashi',
    'Agyaga',
    'Agyaragun Tofa',
    'Akiri',
    'Akpanaja',
    'Akum',
    'Akwanga East',
    'Akwanga West',
    'Alagye I',
    'Alagye Ii',
    'Aloce/ginda',
    'Alogani',
    'Aloshi',
    'Amba',
    'Amiri',
    'Ancho Nighaan',
    'Anchobaba',
    'Andaha',
    'Ang.rimi',
    'Angwan Iya I',
    'Angwan Iya Ii',
    'Ara I',
    'Ara Ii',
    'Arikya',
    'Arum',
    'Ashigie',
    'Aso / Kodape',
    'Assakio',
    'Azara',
    'Bakin Rijiya/akurba/sarkin Pada',
    'Bassa',
    'Bugakarmo',
    'Chiroma',
    'Dari',
    'Dausu',
    'Deddere/riri',
    'Doka I',
    'Doka Ii',
    'Duduguru',
    'Ende',
    'Gadagwa',
    'Galadima',
    'Gangare Tudu',
    'Garaku',
    'Gayam',
    'Gidan Ausa I',
    'Gidan Ausa Ii',
    'Gitata',
    'Gitta',
    'Giza Galadima',
    'Giza Madaki',
    'Gudi',
    'Gurku/kabusu',
    'Guto/aisa',
    'Gwadenye',
    'Gwanje .gwanje',
    'Gwargwada',
    'Hadari',
    'Igga/burumburum',
    'Ikka Wangibi',
    'Iwagu',
    'Jangaru',
    'Jigwada',
    'Jimiya',
    'Kadarko',
    'Kafin Shanu/betti',
    'Kagbu Wana',
    'Kanah/ondo/apawu',
    'Kanje/abuni',
    'Kanyehu',
    'Karshi I',
    'Karshi Ii',
    'Karu',
    'Katakpa I',
    'Keffi Town East / Kofar Goriya',
    'Keffin/wambai',
    'Kofar Gwari',
    'Kokona',
    'Konvah',
    'Koya / Kana',
    'Kwara',
    'Kyakale',
    'Lambaga/arikpa',
    'Laminga',
    'Liman Abaji',
    'Lizzin Keffi/ezzen',
    'Loko',
    'Mada Station',
    'Madaki',
    'Makama',
    'Makwangiji',
    'Mangar',
    'Moroa',
    'Nakere',
    'Nasarawa Central',
    'Nasarawa East',
    'Nasarawa Eggon',
    'Nasarawa Main Town',
    'Nasarawa North',
    'Ningo / Bohar',
    'Ninkoro',
    'Nunku',
    'Obene',
    'Obi',
    'Odu',
    'Oki',
    'Panda / Kare',
    'Ribi',
    'Rukubi I',
    'Rukubi Ii',
    'Sabon Gari',
    'Sarkin Dawaki',
    'Shabu/kwandere',
    'Shafan Abakpa I',
    'Shafan Kwatto I',
    'Shege I',
    'Tattara/kondoro',
    'Toto',
    'Tudun Adabu',
    'Tudun Kofa T.v',
    'Tunga',
    'Tunga/bakono',
    'Ubbe',
    'Udenin',
    'Udenin Gida',
    'Ugya',
    'Uke',
    'Umaisha',
    'Umme',
    'Ungwan Madaki',
    'Wakama',
    'Wakwa',
    'Wamba East',
    'Wamba West',
    'Wayo',
    'Wuse',
    'Yara',
    'Yelwa',
    'Zanwa',
]

export const EXPLOREDATA =[
    'Programmes/Government Initiative',
    'Number Of teachers',
    'Social Economic Status',
    'Infrastructure',
    'Scholarship',
    'Environmental challenges',
    'Performance level'
]

export const REVIEWPOLICIES = [
    'Curriculum',
    'School choice',
    'Allocation of Public Funds',
    'System Evaluation',
    'Student Mobility'
]
  